# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

acme:
  server: https://acme-v02.api.letsencrypt.org/directory
  email:

privateKeySecretRef: letsencrypt-private-key

solvers:
  - dns01:
      # azureDNS:
      #   hostedZoneName: $AZURE_ZONE_NAME
      #   resourceGroupName: $AZURE_RESOURCE_GROUP
      #   subscriptionID: $AZURE_SUBSCRIPTION_ID
      #   environment: AzurePublicCloud
      #   managedIdentity:
      #     clientID: $IDENTITY_CLIENT_ID